FROM python:3.13-bookworm

WORKDIR /app

COPY . .

# using uv as its faster for installing dependencies
RUN pip install --upgrade pip && pip install uv

# similar to pip install
RUN uv add -r requirements.txt

EXPOSE 8888

# make the kernel usable as an interactive kernel
RUN uv run python -m ipykernel install --name project-kernel --display-name "Project Kernel"

# launch jupyterlab with no token and password to make it easy to use as the kernel
CMD ["uv", "run", "jupyter", "lab", "--no-browser", "--ip=0.0.0.0", "--port=8888", "--NotebookApp.token=''", "--NotebookApp.password=''", "--allow-root"]
