# Base Python image
FROM python:3.13-bookworm

WORKDIR /app

COPY . .

# using uv as its faster for installing dependencies
RUN pip install --upgrade pip && pip install uv

# similar to pip install
RUN uv add -r requirements.txt

CMD ["uv", "run", "kedro", "run"]