# Base Python image
FROM python:3.13-slim-bookworm

WORKDIR /app

COPY . .

RUN pip install --upgrade pip && pip install uv

RUN uv add -r requirements.txt

CMD ["uv", "run", "kedro", "run"]
