data_cleaning_params:
  # AGE
  create_age_unk: False
  age_knn_impute: True
  age_knn_impute_settings: # Keyword arguments for KNNImputer
    n_neighbors: 2
    weights: "distance"

  # PREVIOUS CONTACT DAYS
  create_previously_contacted: True

  # PERSONAL_LOAN (fill, drop, impute)
  personal_loan_cleaning: "impute"

encoding_params:
  # Higher priority encoding at top
  one_hot_encode: True
  label_encode: False

# model_params: