data_cleaning_params:
  # AGE
  # Create the age_unk columns (True, False)
  create_age_unk: False
  # Do KNN imputation to impute missing ages (True False)
  age_knn_impute: True
  age_knn_impute_settings:  
    # Keyword arguments for KNNImputer from sklearn.impute
    n_neighbors: 2
    weights: "distance"

  # PREVIOUS CONTACT DAYS
  # Create previously_contacted column (True, False)
  create_previously_contacted: True

  # PERSONAL_LOAN 
  # Cleaning mode for personal_loan column (fill, drop, impute)
  personal_loan_cleaning: "impute"

encoding_params:
  # Higher priority encoding at top 
  # Whether to use specified encoding process (True, False)
  one_hot_encode: True
  label_encode: False

model_params:
  decision_tree_model: True
  decision_tree_settings:
    # Settings here

  randforest_model: True
  randforest_settings:
    # Settings here