data_cleaning_params:
  # AGE
  create_age_unk: True
  # PERSONAL LOAN
  personal_loan_knn_impute: True
  # PREVIOUS CONTACT DAYS
  create_previously_contacted: True

encoding_params:
  # Higher priority encoding at top
  one_hot_encode: True
  label_encode: False

# model_params: